// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "sotftek-serverless",
    "version": "1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "api",
        "description": "",
        "operationId": "api.get./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/obtenerJedi": {
      "get": {
        "summary": "getJedi",
        "description": "",
        "operationId": "getJedi.get./obtenerJedi",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/crearJediPeruano": {
      "post": {
        "summary": "createPeruvianJedi",
        "description": "",
        "operationId": "createPeruvianJedi.post./crearJediPeruano",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/obtenerJedisPeruanos": {
      "get": {
        "summary": "getPeruvianJedis",
        "description": "",
        "operationId": "getPeruvianJedis.get./obtenerJedisPeruanos",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};